[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "course"
version = "0.1.0"
dependencies = ["numpy>=1.25"]

[tool.setuptools.packages.find]
where = ["."]
include = ["course*"]
